language: node_js
node_js:
  - "8.5"
os: osx

branches:
  only:
    - master
before_install:

services:
  mongodb

addons:
  chrome: stable

before_script:
- cd smart-note 
- npm install -g @angular/cli
- npm install -g karma
- npm install

script:
  npm run test
  # sh build.sh

notifications:
  email:
    on_failure: change
    on_success: change
